apiVersion: apps/v1
kind: delpoyment
metadata:
  name: nginx
spec:
  replica: 2
  selector:
    matchlabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerport: 80