apiVersion: apps/v1
kind: Deployment
metadata:
  name: DB-deployment
spec: 
  replicas: 2
  selector:
    matchLabels: 
      tier: db
  template:
    metadata: 
      labels: 
        tier: db
  spec:
    containers:
    - name: db-container
      image: postgres
      ports:
      - containerPort: 5432
      env:
      - name: postgres-password
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: password

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    tier: db
  ports:
  - port: 5432
    targetPort: 5432
        