apiVersion: apps/v1
kind: Deployment
metadata:
  name:lms-fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    meatadata:
      app: frontend
    spec:
      containers:
        name: lms-fe-container
        image: lokesh070/lms-fe
        imagePullPolicy: Always
        ports:
        - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80